# TODO: Create pydantic model for config
# TODO: Use default_scorer and default_metric in template.py
# TODO: Make S3 bucket name an environment variable
prod:
  evaluations:
    agents:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    assistants:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    coding:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    cybersecurity:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    knowledge:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    mathematics:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    reasoning:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    safeguards:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json

stage:
  evaluations:
    agents:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    assistants:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    coding:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    cybersecurity:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    knowledge:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    mathematics:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    reasoning:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
    safeguards:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json

dev:
  evaluations:
    agents:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/3.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/4.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/5.json
    assistants:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/3.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/4.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/5.json
    coding:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/3.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/4.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/5.json
    cybersecurity:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/3.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/4.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/5.json
    knowledge:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/3.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/4.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/5.json
    mathematics:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/3.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/4.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/5.json
    reasoning:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/3.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/4.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/5.json
    safeguards:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - s3://inspect-evals-dashboard/dev/pubmedqa/1.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/2.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/3.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/4.json
          - s3://inspect-evals-dashboard/dev/pubmedqa/5.json

test:
  evaluations:
    agents:
      - name: pubmedqa
        default_scorer: choice
        default_metric: accuracy
        paths: 
          - test/data/pubmedqa/1.json
          - test/data/pubmedqa/2.json
